insert into user (login_id, password, username, nickname, email, role, created_time, modified_time) values ('zx8571', '{noop}shvhsy8571', '운영자', '운영자', 'test@test.com', 'ADMIN', '2023-07-15 04:52:36', '2023-07-11 08:24:10');

insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Curabitur in libero ut massa volutpat convallis.', 1, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', false, false, '2023-07-15 04:52:36', '2023-07-11 08:24:10');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Phasellus in felis.', 1, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', true, true, '2022-12-17 13:09:16', '2022-11-24 09:09:27');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Aliquam sit amet diam in magna bibendum imperdiet.', 1, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', true, true, '2022-12-12 01:59:24', '2022-10-25 06:25:12');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Quisque porta volutpat erat.', 1, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', false, true, '2023-04-25 08:02:13', '2023-04-06 20:06:29');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Sed ante.', 1, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', false, false, '2023-01-13 08:16:03', '2022-11-18 12:07:11');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', false, false, '2022-12-07 22:57:51', '2023-08-15 06:29:20');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Cras pellentesque volutpat dui.', 1, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', true, true, '2023-01-16 10:19:08', '2022-11-19 03:24:53');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Mauris lacinia sapien quis libero.', 1, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', false, false, '2023-07-10 15:52:36', '2023-09-18 04:14:49');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 1, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', true, false, '2023-05-27 06:13:05', '2023-03-10 04:16:56');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Mauris ullamcorper purus sit amet nulla.', 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', false, true, '2023-09-12 06:27:35', '2023-07-16 04:54:22');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', false, false, '2023-02-11 12:22:52', '2023-03-25 12:19:49');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', false, false, '2022-11-15 01:19:31', '2023-09-01 10:12:50');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Sed ante.', 1, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', true, false, '2023-02-17 14:02:00', '2023-06-22 20:09:34');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Curabitur convallis.', 1, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', true, true, '2023-03-15 23:27:08', '2022-12-06 10:35:22');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Maecenas ut massa quis augue luctus tincidunt.', 1, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', true, false, '2023-01-06 07:48:57', '2023-05-14 04:55:04');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Morbi non quam nec dui luctus rutrum.', 1, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', true, true, '2023-03-15 08:22:43', '2022-12-12 10:04:41');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('In sagittis dui vel nisl.', 1, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', true, false, '2023-01-08 03:47:46', '2023-03-28 03:50:37');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Morbi porttitor lorem id ligula.', 1, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', true, false, '2023-06-08 09:13:12', '2023-01-13 04:27:32');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Sed vel enim sit amet nunc viverra dapibus.', 1, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', false, false, '2023-05-18 01:21:30', '2023-03-21 04:39:37');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Duis aliquam convallis nunc.', 1, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', true, true, '2023-04-26 19:56:59', '2023-06-17 03:33:30');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Etiam pretium iaculis justo.', 1, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', true, true, '2023-02-01 12:14:36', '2022-10-22 09:24:57');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 1, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', false, true, '2023-08-18 14:05:39', '2022-11-22 19:46:08');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Fusce posuere felis sed lacus.', 1, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', true, true, '2023-01-15 06:43:01', '2022-11-05 19:32:58');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 1, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', true, true, '2023-03-19 01:25:19', '2023-03-28 13:07:23');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Phasellus sit amet erat.', 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', false, true, '2023-02-10 10:20:37', '2022-11-16 08:41:28');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nulla facilisi.', 1, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', false, false, '2022-12-21 06:56:30', '2023-06-22 11:57:26');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Suspendisse potenti.', 1, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', false, false, '2022-12-28 08:43:23', '2023-01-30 08:18:49');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Mauris sit amet eros.', 1, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', true, true, '2023-10-07 13:40:22', '2022-12-18 23:38:56');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Proin interdum mauris non ligula pellentesque ultrices.', 1, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', false, true, '2023-05-20 06:06:48', '2023-03-12 21:48:28');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Praesent id massa id nisl venenatis lacinia.', 1, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', true, true, '2022-11-10 22:06:37', '2023-09-16 01:40:34');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Cras pellentesque volutpat dui.', 1, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', true, false, '2022-10-16 20:39:11', '2023-05-03 00:04:17');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Fusce consequat.', 1, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', true, false, '2023-08-06 21:41:56', '2023-05-31 16:18:32');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Maecenas ut massa quis augue luctus tincidunt.', 1, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', false, false, '2022-10-16 16:16:00', '2022-12-08 07:44:15');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Vestibulum ac est lacinia nisi venenatis tristique.', 1, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', true, true, '2022-12-22 04:19:18', '2023-02-19 02:09:57');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 1, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', false, false, '2023-02-05 13:11:12', '2023-04-05 14:08:11');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('In hac habitasse platea dictumst.', 1, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', false, false, '2022-11-21 19:55:48', '2023-04-30 09:55:52');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', true, false, '2023-10-01 18:49:56', '2023-08-15 21:36:31');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', false, true, '2023-01-19 14:40:30', '2023-06-15 03:24:57');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Phasellus sit amet erat.', 1, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', true, true, '2023-03-12 07:53:39', '2023-09-13 01:47:19');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nam nulla.', 1, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', true, true, '2023-09-16 14:18:33', '2023-08-20 20:10:47');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('In hac habitasse platea dictumst.', 1, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', false, true, '2023-08-29 19:24:34', '2022-10-16 04:24:09');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 1, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', false, true, '2023-06-17 06:35:02', '2023-08-25 00:19:11');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nulla ut erat id mauris vulputate elementum.', 1, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', false, false, '2022-11-13 07:06:50', '2023-09-21 23:35:10');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 1, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', false, false, '2022-10-14 02:43:11', '2023-04-29 05:57:19');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Vestibulum ac est lacinia nisi venenatis tristique.', 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', true, false, '2023-10-06 02:59:09', '2023-01-09 05:36:56');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nulla tempus.', 1, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', true, true, '2023-08-14 15:55:28', '2023-09-10 18:19:54');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Pellentesque eget nunc.', 1, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', true, false, '2023-05-11 08:01:22', '2023-02-05 02:52:52');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Aliquam non mauris.', 1, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', true, false, '2022-12-08 07:43:07', '2023-01-25 11:06:29');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nullam molestie nibh in lectus.', 1, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', true, false, '2023-08-18 10:14:16', '2022-11-06 19:06:26');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Integer tincidunt ante vel ipsum.', 1, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', true, true, '2022-12-22 04:33:50', '2022-10-20 07:37:05');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('In blandit ultrices enim.', 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', true, false, '2023-01-17 09:26:45', '2023-09-05 00:24:05');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Etiam faucibus cursus urna.', 1, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', true, true, '2023-04-19 12:10:32', '2023-01-27 14:55:03');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', true, true, '2023-08-14 13:16:48', '2022-12-05 20:46:17');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', true, false, '2023-02-20 09:11:52', '2023-10-10 16:19:00');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nulla facilisi.', 1, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', false, false, '2023-01-28 08:39:48', '2023-05-26 21:03:31');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Ut tellus.', 1, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', false, false, '2023-08-31 21:32:21', '2023-06-01 02:48:40');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Etiam justo.', 1, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', false, false, '2022-11-16 03:51:20', '2023-08-10 15:30:31');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', true, false, '2023-02-17 13:18:22', '2023-07-16 10:57:29');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 1, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', true, false, '2022-11-05 20:33:14', '2022-10-30 18:19:41');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Pellentesque viverra pede ac diam.', 1, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', true, false, '2023-08-09 01:44:54', '2022-10-26 20:07:48');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nam dui.', 1, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', true, false, '2023-04-08 11:03:30', '2023-04-21 15:11:41');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Aenean fermentum.', 1, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', false, false, '2023-06-29 15:22:37', '2023-09-16 22:00:39');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Praesent blandit.', 1, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', true, true, '2022-11-25 10:03:39', '2023-01-26 06:56:44');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Integer non velit.', 1, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', true, false, '2023-08-21 05:12:53', '2023-02-11 12:28:39');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Proin interdum mauris non ligula pellentesque ultrices.', 1, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', false, false, '2023-07-15 09:49:48', '2023-10-10 15:11:28');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Donec ut mauris eget massa tempor convallis.', 1, 'Fusce consequat. Nulla nisl. Nunc nisl.', false, false, '2023-03-22 00:27:26', '2022-11-24 13:38:23');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Maecenas pulvinar lobortis est.', 1, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', false, true, '2023-06-30 18:31:09', '2023-06-23 02:14:09');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Aenean fermentum.', 1, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', false, true, '2023-03-08 02:23:50', '2022-12-18 23:10:41');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Maecenas tincidunt lacus at velit.', 1, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', true, false, '2023-04-07 10:28:48', '2023-09-28 04:52:26');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Proin interdum mauris non ligula pellentesque ultrices.', 1, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', true, true, '2023-06-15 15:28:33', '2023-07-04 05:50:14');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('In hac habitasse platea dictumst.', 1, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', true, false, '2023-09-11 10:41:39', '2023-04-06 04:22:45');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 1, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', false, true, '2022-12-10 06:52:36', '2023-03-01 12:42:14');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Morbi vel lectus in quam fringilla rhoncus.', 1, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', true, false, '2023-04-15 22:35:19', '2023-07-24 04:37:21');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Integer ac neque.', 1, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', false, false, '2023-08-28 03:01:02', '2022-12-09 01:04:09');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Donec posuere metus vitae ipsum.', 1, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', true, false, '2022-10-28 14:17:00', '2023-01-17 14:56:09');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Sed sagittis.', 1, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', true, false, '2022-12-29 18:08:38', '2023-02-25 11:25:01');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Sed ante.', 1, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', false, true, '2023-01-31 10:05:19', '2023-08-03 09:50:19');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('In hac habitasse platea dictumst.', 1, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', false, true, '2022-12-10 09:54:38', '2023-01-10 23:34:16');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Vestibulum sed magna at nunc commodo placerat.', 1, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', false, false, '2023-05-11 11:31:37', '2023-06-11 03:18:00');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', false, false, '2023-09-27 20:12:25', '2022-11-05 11:41:23');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Aliquam sit amet diam in magna bibendum imperdiet.', 1, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', true, false, '2023-02-18 01:31:38', '2023-07-08 00:20:54');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Suspendisse ornare consequat lectus.', 1, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', true, true, '2023-08-14 16:56:32', '2023-09-14 05:28:11');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Cras in purus eu magna vulputate luctus.', 1, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', true, false, '2023-05-22 11:17:25', '2023-09-01 02:08:59');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('In congue.', 1, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', false, false, '2023-01-31 19:51:25', '2023-06-27 05:45:50');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nam dui.', 1, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', true, true, '2023-01-26 08:03:43', '2023-03-26 12:22:32');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Pellentesque eget nunc.', 1, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', false, true, '2023-06-15 00:01:44', '2023-07-26 18:34:32');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', false, true, '2023-03-06 22:55:41', '2023-02-14 18:03:07');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 1, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', true, true, '2022-11-14 03:40:33', '2023-05-01 23:55:49');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Morbi ut odio.', 1, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', true, true, '2023-02-15 12:55:40', '2023-01-19 04:48:17');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Proin risus.', 1, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', true, false, '2023-06-08 23:50:13', '2023-08-06 05:39:51');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Morbi ut odio.', 1, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', false, false, '2022-12-26 08:09:53', '2023-02-19 16:27:00');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Phasellus in felis.', 1, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', false, true, '2023-06-07 13:47:16', '2023-06-20 01:27:46');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Pellentesque eget nunc.', 1, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', true, false, '2023-07-25 00:50:03', '2023-05-06 18:36:21');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Quisque id justo sit amet sapien dignissim vestibulum.', 1, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', true, true, '2022-11-05 13:19:24', '2023-02-14 09:04:06');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', false, false, '2022-11-05 18:57:34', '2022-11-01 19:32:35');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 1, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', true, true, '2023-04-01 20:49:43', '2023-02-04 03:51:48');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Aliquam quis turpis eget elit sodales scelerisque.', 1, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', true, false, '2023-04-01 16:10:35', '2023-08-20 23:30:05');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nulla tempus.', 1, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', true, true, '2022-12-24 00:07:05', '2022-12-03 03:24:11');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Donec ut dolor.', 1, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', false, false, '2023-08-20 03:14:03', '2023-02-06 05:07:16');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Duis at velit eu est congue elementum.', 1, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', false, true, '2022-10-24 08:54:25', '2023-04-19 22:04:21');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nam nulla.', 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', false, false, '2023-07-26 12:34:02', '2023-05-15 13:48:54');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nulla suscipit ligula in lacus.', 1, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', true, true, '2023-10-07 13:26:32', '2023-07-05 07:22:47');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Aenean auctor gravida sem.', 1, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', false, false, '2023-05-27 00:28:44', '2022-12-23 19:38:15');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Pellentesque ultrices mattis odio.', 1, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', false, false, '2023-06-27 01:00:11', '2023-10-06 02:20:55');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Duis mattis egestas metus.', 1, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', true, true, '2022-11-08 10:59:48', '2023-09-29 20:49:24');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 1, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', false, false, '2022-12-11 20:08:12', '2023-01-26 04:41:33');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Proin eu mi.', 1, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', false, true, '2023-04-17 10:38:37', '2023-03-23 12:53:19');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Morbi vel lectus in quam fringilla rhoncus.', 1, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', false, true, '2023-08-30 22:12:17', '2023-09-11 03:29:49');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', true, true, '2022-11-07 00:40:51', '2023-09-15 03:38:11');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 1, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', false, false, '2023-08-05 10:34:00', '2022-11-17 20:04:43');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Quisque porta volutpat erat.', 1, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', false, false, '2023-05-07 10:37:30', '2022-12-20 11:14:54');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', false, false, '2022-12-14 02:44:48', '2023-09-17 00:10:45');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Vestibulum rutrum rutrum neque.', 1, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', true, true, '2023-07-02 03:49:47', '2022-10-13 10:07:28');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Pellentesque at nulla.', 1, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', false, false, '2023-08-04 22:15:32', '2022-12-03 03:20:55');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Pellentesque viverra pede ac diam.', 1, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', true, true, '2023-04-29 03:12:33', '2023-04-18 19:17:25');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nullam molestie nibh in lectus.', 1, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', false, false, '2023-02-03 00:34:12', '2023-02-23 08:16:45');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', true, false, '2023-03-15 03:49:29', '2022-12-20 07:19:59');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Nunc rhoncus dui vel sem.', 1, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', true, true, '2023-02-10 17:57:11', '2023-07-09 13:01:07');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 1, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', false, true, '2023-08-09 05:23:11', '2023-01-11 23:29:58');
insert into article (title, user_id, content, delete_yn, update_yn, created_time, modified_time) values ('Maecenas rhoncus aliquam lacus.', 1, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', false, false, '2023-07-06 18:57:03', '2023-06-23 08:00:24');

INSERT INTO disease (id, d_name, solution, src) VALUES ('1Tomato_Bacterial_spot', '토마토 세균성점무늬병',
                                                        '종자를 50℃의 물에 25분간 침지하여 소독하고, 재배는 배수가 잘 되는 비옥한 토지를 선택하여 퇴비를 많이 넣어서 재배한다. 하우스에서는 저온기라도 다습하면 발생하게 되므로 환기와 통풍에 힘쓰고 급격한 온도변화가 없도록 한다. 약제방제는 농업용 항생제인 농용신수화제 1,200배액, 요네폰수화제 500배액, 가스란수화제 1,000배액을 발병초기에 2∼3회 살포하면 효과적이다.',
                                                        '/result/1Tomato_Bacterial_spot.JPG');

INSERT INTO disease (id, d_name, solution, src) VALUES ('2Tomato_Early_blight', '토마토 겹둥근무늬병',
                                                        '모판에서부터 발생되기 시작하므로 예방위주로 방제를 해야 한다. 또 이 병은 비료상태에 민감하므로 비배관리에 주의해야 한다. 방제약제로는 쿠퍼수화제 500배액, 놀란수화제 1,000배액 등이 있다.',
                                                        '/result/2Tomato_Early_blight.JPG');

INSERT INTO disease (id, d_name, solution, src) VALUES ('3Tomato_Late_blight', '토마토 역병',
                                                        '모판에서부터 온도, 습도 관리에 주의하여 저온 다습이 되지 않도록 한다. 특히 11월 - 다음해 4월에 걸쳐 저온기의 재배는 저온다습에 주의한다. ',
                                                        '/result/3Tomato_Late_blight.JPG');

INSERT INTO disease (id, d_name, solution, src) VALUES ('4Tomato_Leaf_Mold', '토마토 잎곰팡이병',
                                                        '환기에 주의하여 습도를 낮추어주고 지면에는 비닐멀칭을 해서 지표면의 습기가 올라가지 않도록 한다. 점적관수를 이용해서 비닐 멀칭 밑으로 관수되게 하여 습기를 낯추는데 중점을 두어야 한다. 종자는 건전주에서 채종하여 사용하고 종자소독을 철저히 한다. 사전예방으로 모판 때부터 10-15일 간격으로 약제를 살포한다',
                                                        '/result/4Tomato_Leaf_Mold.JPG');

INSERT INTO disease (id, d_name, solution, src) VALUES ('5Tomato_Septoria_leaf_spot', '토마토 흰무늬병',
                                                        '종자를 선별하고, 소독하여 파종한다 재배 시 균형시비를 한다. 병든 잎은 조기에 제거한다. 온실재배 시 내부가 다습하지 않도록 환기를 한다.',
                                                        '/result/5Tomato_Septoria_leaf_spot.JPG');

INSERT INTO disease (id, d_name, solution, src) VALUES ('6Tomato_Spider_Mites_Two', '토마토 점박이응애',
                                                        '3월 이전에는 기계유제를 이용하여 방제하고. 5월경에 응애들의 밀도가 증가하므로 알이나 유충 등에 효과가 좋은 약제를 살포하여야 한다. 온도조건이 좋아지는 시기인 7월 상순경에 발생밀도를 관찰하여 엽당 2-3마리 이상이면 2차방제를 하여야 한다. 이 때 제대로 방제가 안 되면 7월 하순-8월에 큰 피해를 입게 된다. 8월 상-중순 고온기로서 엽당 3-4마리 이상이면 약제를 살포하여야 한다',
                                                        '/result/6Tomato_Spider_Mites_Two.JPG');

INSERT INTO disease (id, d_name, solution, src) VALUES ('7Tomato_Target_Spot', '토마토 표적 반점',
                                                        '클로로탈로닐, 만코제브, 옥시염화구리를 함유한 제품은 연구 실험에서 표적 지점을 잘 제어하는 것으로 나타났습니다. 스트로빌루린 살진균제인 azoxystrobin 및 pyraclostrobin, 살진균제 boscalid 및 전신 획득 저항(SAR) 유발제인 acibenzolar-S-methyl도 표적 지점을 잘 제어하는 것으로 나타났습니다.',
                                                        '/result/7Tomato_Target_Spot.JPG');

INSERT INTO disease (id, d_name, solution, src) VALUES ('8Tomato_YellowLeaf', '토마토황화잎말림바이러스',
                                                        '하우스 내 및 주변의 철저한 관리가 필요하다. 토마토 재배 시설 주변에는 담배가루가 좋아하는 작물을 심지 말아야하며, 토마토 재배 시설 주변에 서식하는 토마토황화잎말림병의 중간 다리 역할을 하는 쑥 등 잡초들을 제거해야한다. 토마토 시설의 측창, 천창 및 출입문은 60메쉬 망을 설치하여 담배가루이 출입 및 외부로부터 유입을 차단해야한다.',
                                                        '/result/8Tomato_YellowLeaf.JPG');

INSERT INTO disease (id, d_name, solution, src) VALUES ('9Tomato_Healthy', '건강한 토마토', '이상없음', '/result/9Tomato_Healthy.JPG');